//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 08:12:43 PM MSD 
//


package wordtutor.xml.dict;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="foreignWord" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nativeWord" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="learned" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="idSound" type="{http://www.w3.org/2001/XMLSchema}int"/> *         
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wordType", propOrder = {
    "foreignWord",
    "nativeWord",
    "score",
    "learned",
    "idSound"    
})
public class WordType {
    @XmlElement(required = true)
    protected String foreignWord;
    @XmlElement(required = true)
    protected String nativeWord;
    @XmlElement(required = true)    
    protected int score;
    @XmlElement(required = true)    
    protected int learned;
    @XmlElement(required = true)    
    protected int idSound;    

    /**
     * Gets the value of the foreignWord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignWord() {
        return foreignWord;
    }

    /**
     * Sets the value of the foreignWord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignWord(String value) {
        this.foreignWord = value;
    }

    /**
     * Gets the value of the nativeWord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNativeWord() {
        return nativeWord;
    }

    /**
     * Sets the value of the nativeWord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNativeWord(String value) {
        this.nativeWord = value;
    }

    /**
     * Gets the value of the score property.
     * 
     */
    public int getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     */
    public void setScore(int value) {
        this.score = value;
    }

    /**
     * Gets the value of the learned property.
     * 
     */
    public int getLearned() {
        return learned;
    }

    /**
     * Sets the value of the learned property.
     * 
     */
    public void setLearned(int value) {
        this.learned = value;
    }


    /**
     * Gets the value of the idSound property.
     * 
     */
    public int getIdSound() {
        return idSound;
    }

    /**
     * Sets the value of the idSound property.
     * 
     */
    public void setIdSound(int value) {
        this.idSound = value;
    }
    
}
