//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.01 at 08:36:17 PM MSD 
//


package wordtutor.xml.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wordsInLesson" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="incScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="decScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="strictMode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="examMode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="keyboard" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settingsType", propOrder = {
    "wordsInLesson",
    "autoSuggest",    
    "maxScore",
    "incScore",
    "decScore",
    "direction",
    "strictMode",
    "examMode",
    "keyboard",
    "unlearned",    
    "hardest",
    "random"
})
public class SettingsType {
	/** maxScore, decScore to remove and exhaustiveLearn - change name to EXAM 
	 * 
	 */
    @XmlElement(required = true)
	  protected int wordsInLesson;
    @XmlElement(required = true)    
    protected int maxScore;
    @XmlElement(required = true)
    protected int incScore;
    @XmlElement(required = true)
    protected int decScore;
    @XmlElement(required = true)
    protected int direction;
    @XmlElement(required = true)
    protected int strictMode;  
    @XmlElement(required = true)
    protected int examMode;
    @XmlElement(required = true)
    protected int keyboard;
    @XmlElement(required = true)
    protected int unlearned;   
    @XmlElement(required = true)
    protected int hardest;
    @XmlElement(required = true)
    protected int random;    
    @XmlElement(required = true)
	protected int autoSuggest;
    

		/** Gets additional keyboard type (language type) 
     * 
     * @return
     */
    public int getKeyboard() {
		return keyboard;
	}
	/** Sets additional keyboard type (language type)
     * 		enum : wordtutor.util.keybuttons.KeyboardButtonType
     * 
     * @param keyboard
     */
	public void setKeyboard(int keyboard) {
		this.keyboard = keyboard;
	}
	/** is this Exam Mode / otherwise this is Lesson Mode
     * 
     * 
     */
    public int getExamMode() {
		return examMode;
	}

	public void setExamMode(int examMode) {
		this.examMode = examMode;
	}

	/**
     * Gets the value of the wordsInLesson property.
     * 
     */
    public int getWordsInLesson() {
        return wordsInLesson;
    }

    /**
     * Sets the value of the wordsInLesson property.
     * 
     */
    public void setWordsInLesson(int value) {
        this.wordsInLesson = value;
    }

    /**
     * Gets the value of the maxScore property.
     * 
     */
    public int getMaxScore() {
        return maxScore;
    }

    /**
     * Sets the value of the maxScore property.
     * 
h     */
    public void setMaxScore(int value) {
        this.maxScore = value;
    }

    /**
     * Gets the value of the incScore property.
     * 
     */
    public int getIncScore() {
        return incScore;
    }

    /**
     * Sets the value of the incScore property.
     * 
     */
    public void setIncScore(int value) {
        this.incScore = value;
    }

    /**
     * Gets the value of the decScore property.
     * 
     */
    public int getDecScore() {
        return decScore;
    }

    /**
     * Sets the value of the decScore property.
     * 
     */
    public void setDecScore(int value) {
        this.decScore = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     */
    public int getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     */
    public void setDirection(int value) {
        this.direction = value;
    }

    /**
     * Gets the value of the strictMode property.
     * 
     */
    public int getStrictMode() {
        return strictMode;
    }

    /**
     * Sets the value of the strictMode property.
     * 
     */
    public void setStrictMode(int value) {
        this.strictMode = value;
    }
    /**
     * 
     */
    public int getUnlearned() {
			return unlearned;
		}
    /**
     * 
     * @param unlearned
     */
		public void setUnlearned(int unlearned) {
			this.unlearned = unlearned;
		}

		/** either random or hardest
		 * 
		 * @return
		 */
		public int getHardest() {
			return hardest;
		}
		
		public void setHardest(int hardest) {
			this.hardest = hardest;
		}
		/** the minimum number of characters to autosuggest right answer 
		 * 
		 * @return
		 */
		public int getAutoSuggest() {
			return autoSuggest;
		}
		public void setAutoSuggest(int autoSuggest) {
			this.autoSuggest = autoSuggest;
		}
		
		/** either hardest or random
		 *  
		 * @return
		 */
		public int getRandom() {
				return random;
		}
		public void setRandom(int random) {
			this.random = random;
		}
		
}
